name: 'EzReleases'
description: 'Automated releases with semantic versioning'
inputs:
  repo_token:
    required: true
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'src/build/index.js'
branding:
  color: 'blue'
  icon: 'refresh-cw'
