name: Build and Tag Action

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build-action:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: install dependencies
          run: yarn

        - name: build action
          run: yarn build

        - name: commit builds
          uses: EndBug/add-and-commit@v4
          with:
            author_name: nionata
            author_email: nionata@ufl.edu
            message: Built latest 
            add: "*"
            ref: master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag-master:
    needs: build-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Tag Master
        uses: nionata/EzReleases@master
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"